[global]
pid = /tmp/php-fpm.pid
error_log = /dev/stderr
daemonize = no

[www]
user = root
group = root
listen = 127.0.0.1:9000
clear_env = no

pm = ondemand
pm.max_children = 5
pm.process_idle_timeout = 10s